changelog:
  exclude:
    labels:
      - chore
      - docs
      - ci
      - ci-failure
      - test
      - dependencies
      - internal

  categories:
    - title: Added
      labels:
        - feature
        - enhancement

    - title: Changed
      labels:
        - changed
        - refactor

    - title: Fixed
      labels:
        - bug
        - fix

    - title: Security
      labels:
        - security

    - title: Breaking
      labels:
        - breaking
