name: Bug report
description: Report a reproducible bug
title: "Bug: <short summary>"
labels: ["bug"]
assignees: []

body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: One-sentence description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happens instead?
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to …
        2. Click …
        3. See error
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - local dev
        - staging
        - production
    validations:
      required: true

  - type: input
    id: browser-os
    attributes:
      label: Browser + OS
      placeholder: "e.g. Chrome 125 / Windows 11"
    validations:
      required: false

  - type: dropdown
    id: regression
    attributes:
      label: Regression?
      description: Did this work before a recent change?
      options:
        - unknown
        - "yes"
        - "no"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - low
        - medium
        - high
        - blocker
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / error output
      description: Paste the first error line or relevant log snippet.
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / screen recording
      description: Attach images or link to a recording.
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if any)
    validations:
      required: false
